# Generated by Django 6.0.3 on 2026-03-15 12:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_index=True,
                        max_length=255,
                        validators=[django.core.validators.MinLengthValidator(5)],
                        verbose_name="Recipe title",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        db_index=True,
                        validators=[django.core.validators.MaxLengthValidator(2000)],
                        verbose_name="Recipe description",
                    ),
                ),
                (
                    "ingredients",
                    models.TextField(
                        validators=[django.core.validators.MaxLengthValidator(2000)],
                        verbose_name="Recipe ingredients",
                    ),
                ),
                (
                    "instructions",
                    models.TextField(
                        validators=[django.core.validators.MaxLengthValidator(2000)],
                        verbose_name="Recipe instructions",
                    ),
                ),
                (
                    "cooking_time",
                    models.PositiveIntegerField(verbose_name="Recipe cooking time"),
                ),
                ("views", models.PositiveIntegerField(verbose_name="Recipe views")),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipe_author",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Recipe cooking time",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recipe",
                "verbose_name_plural": "Recipies",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RecipeImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="recipe_images/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipe_images",
                        to="kitchen.recipe",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="recipe",
            index=models.Index(
                fields=["title", "description"], name="kitchen_rec_title_973439_idx"
            ),
        ),
    ]
