# Generated by Django 6.0.3 on 2026-03-15 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipe_author",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Recipe Author",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="views",
            field=models.PositiveIntegerField(default=0, verbose_name="Recipe views"),
        ),
        migrations.CreateModel(
            name="RecipeComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(db_index=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipecomment_author",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Recipe Comment author",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recipe Comment",
                "verbose_name_plural": "Recipe Comments",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["author", "text"], name="kitchen_rec_author__2cfa53_idx"
                    )
                ],
            },
        ),
    ]
