# Generated by Django 6.0.3 on 2026-03-15 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen", "0002_alter_recipe_author_alter_recipe_views_recipecomment"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipecomment",
            name="recipe",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipecomment_recipe",
                to="kitchen.recipe",
                verbose_name="Recipe",
            ),
            preserve_default=False,
        ),
    ]
